apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dtoo
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0020-tenant/tkrw-pr712-0075-0020-app/devfile-sample-dtoo@sha256:39d04a3763e8c21c4c0531de05fe71391fa57f90c97bbc04d9e9f9897f6cfd56
        name: my-nodejs
        resources: {}
status: {}
